Add support for CSS `lh` and `rlh` units.
dart-lang/csslib pull request #173
Opened 2023-02-09 18:34 UTC by MH15

Adds support for line height computed units.

Supported only in [Chrome](https://caniuse.com/?search=lh%20unit) however it is part of the [W3 CSS spec].

2023-02-13 22:03 UTC, leonsenft requested changes

2023-02-13 22:03 UTC, leonsenft commented on lib/src/tree.dart
> +      [int unit = TokenKind.UNIT_LENGTH_PX])
Why the default argument that will immediately fail the assert?

It looks like this just mirrors the existing terms, but I see no reason for this pattern. Consider just making this a required parameter with no default?

2023-02-14 19:38 UTC, MH15 commented on lib/src/tree.dart
> +      [int unit = TokenKind.UNIT_LENGTH_PX])
Fixed

2023-02-14 20:40 UTC, leonsenft approved these changes

2023-02-14 21:25 UTC, leonsenft commented
I forgot to ask, could you please add a CHANGELOG entry as well under the current `-dev` version?

https://github.com/dart-lang/csslib/blob/main/CHANGELOG.md

2023-02-14 21:26 UTC, leonsenft requested changes
I forgot to ask, could you please add a CHANGELOG entry as well under the current `-dev` version?

https://github.com/dart-lang/csslib/blob/main/CHANGELOG.md

2023-02-14 23:39 UTC, MH15 commented
Changelog fixed

2023-02-15 00:04 UTC, leonsenft approved these changes

2023-02-15 00:15 UTC, merged